version: 2
jobs:
  build:
    working_directory: ~/playground
    docker:
      - image: node
    steps:
      - checkout
      - run: curl -o- -L https://yarnpkg.com/install.sh | bash -s
      - run: yarn install
      - run: yarn test
